version: '3.8'
services:
  calculator:
    build: .
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./dist:/dist
    networks:
      - ifrsNetwork
    depends_on:
      - database
  database:
    image:
      postgres:12
    restart:
      always
    networks:
      - ifrsNetwork
    expose:
      - "5432"
    volumes:
      - ./dbData:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'ZZZXXX5!#~a'
      POSTGRES_DB: 'leasingdepositsdb'
networks:
  ifrsNetwork: